import Head from 'next/head'
import Header from '../Components/Header'
import Nav from '../Components/Nav'
import Results from '../Components/Results'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <Nav/>

      <Results/>
    </div>
  )
}
